# Generated by Django 5.2.11 on 2026-02-04 05:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age_group_name', models.CharField(choices=[('CHILDREN', 'Children'), ('TEEN', 'Teen'), ('ADULT_1', 'Adult 1'), ('ADULT_2', 'Adult 2'), ('ADULT_3', 'Adult 3'), ('ADULT_4', 'Adult 4'), ('ADULT_5', 'Adult 5'), ('SENIOR', 'Senior'), ('ALL', 'All')], max_length=10)),
                ('cover_image_url', models.URLField(blank=True, help_text='Cover image for age group dashboard (used in SEGREGATE_BIBLES)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the age group')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying age groups in dashboard')),
                ('age_group_created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bible_way_age_group',
                'ordering': ['display_order', 'age_group_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category_name', models.CharField(choices=[('SEGREGATE_BIBLES', 'Segregate Bibles'), ('BIBLE_READER', 'BibleReader')], max_length=35)),
                ('cover_image_url', models.URLField(blank=True, help_text='Cover image for dashboard section', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying categories in dashboard')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bible_way_category',
                'ordering': ['display_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language_name', models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('FR', 'French'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('NL', 'Dutch'), ('SV', 'Swedish'), ('PL', 'Polish'), ('EL', 'Greek'), ('AS', 'Assamese'), ('BN', 'Bengali'), ('BRX', 'Bodo'), ('HI', 'Hindi'), ('GU', 'Gujarati'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KOK', 'Konkani'), ('MAI', 'Maithili'), ('ML', 'Malayalam'), ('MNI', 'Manipuri'), ('MR', 'Marathi'), ('NE', 'Nepali'), ('OR', 'Odia'), ('PA', 'Punjabi'), ('SA', 'Sanskrit'), ('SAT', 'Santali'), ('SD', 'Sindhi'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('UR', 'Urdu'), ('DOG', 'Dogri'), ('SW', 'Swahili'), ('AF', 'Afrikaans'), ('HA', 'Hausa'), ('ZU', 'Zulu'), ('YO', 'Yoruba'), ('ZH_CN', 'Chinese (Simplified)'), ('AR', 'Arabic')], default='EN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('redirect_link', models.URLField()),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bible_way_promotion',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('sticker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bible_way_sticker',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('verse_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='Quote of the day', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bible_way_verse',
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('wallpaper_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bible_way_wallpaper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_provider', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('BOTH', 'Both')], default='EMAIL', max_length=10)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('book_order', models.IntegerField(blank=True, default=0, help_text='Order for displaying books in list', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the book is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible_way.agegroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible_way.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible_way.language')),
            ],
            options={
                'db_table': 'bible_way_book',
                'ordering': ['book_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bible_way.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_bookmark',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chapter_number', models.IntegerField(blank=True, default=0, help_text='Chapter number', null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_url', models.URLField(blank=True, help_text='URL/path to the chapter file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., testament: Old/New)', null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL/path to the video file', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible_way.book')),
            ],
            options={
                'db_table': 'bible_way_chapters',
            },
        ),
        migrations.CreateModel(
            name='ChapterFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='bible_way.chapters')),
            ],
            options={
                'db_table': 'bible_way_chapter_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('highlight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('end_block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_offset', models.CharField(max_length=255)),
                ('end_offset', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='yellow', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bible_way.book')),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bible_way.chapters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_highlight',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_post',
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('prayer_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_prayer_request',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bible_way.post')),
                ('prayer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bible_way.prayerrequest')),
            ],
            options={
                'db_table': 'bible_way_comment',
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('promotion_image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('image_type', models.CharField(default='image', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_images', to='bible_way.promotion')),
            ],
            options={
                'db_table': 'bible_way_promotion_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_id', models.UUIDField(blank=True, null=True)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_notes', to='bible_way.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_reading_note',
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('reading_progress_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to='bible_way.book')),
                ('chapter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to='bible_way.chapters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_reading_progress',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='bible_way.post')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_share',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(db_index=True, max_length=20, unique=True)),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('PROFILE', 'Profile')], max_length=10)),
                ('content_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_share_link',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bible_way_testimonial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bible_way.post')),
                ('prayer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bible_way.prayerrequest')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='bible_way.testimonial')),
            ],
            options={
                'db_table': 'bible_way_media',
            },
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bible_way.chapters')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bible_way.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bible_way.post')),
                ('prayer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bible_way.prayerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bible_way.verse')),
            ],
            options={
                'db_table': 'bible_way_reaction',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'age_group'], name='bible_way_b_categor_b46d15_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'language'], name='bible_way_b_categor_849139_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_active'], name='bible_way_b_is_acti_73917c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['share_token'], name='bible_way_s_share_t_817039_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['content_type', 'content_id'], name='bible_way_s_content_da547d_idx'),
        ),
    ]
