# Generated by Django 5.2.11 on 2026-02-04 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('FOLLOW', 'Follow'), ('POST_LIKE', 'Post Like'), ('COMMENT_LIKE', 'Comment Like'), ('PRAYER_REQUEST_LIKE', 'Prayer Request Like'), ('VERSE_LIKE', 'Verse Like'), ('NEW_MESSAGE', 'New Message'), ('COMMENT_ON_POST', 'Comment on Post'), ('COMMENT_ON_PRAYER_REQUEST', 'Comment on Prayer Request'), ('PRAYER_REQUEST_CREATED', 'Prayer Request Created')], max_length=50)),
                ('target_id', models.CharField(help_text='ID of the target object (post_id, comment_id, etc.)', max_length=255)),
                ('target_type', models.CharField(help_text='Type of target (post, comment, message, etc.)', max_length=50)),
                ('conversation_id', models.IntegerField(blank=True, help_text='For message notifications', null=True)),
                ('message_id', models.IntegerField(blank=True, help_text='For message notifications', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='For storing aggregated data (actors_count, actors list, last_actor_id)')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='project_not_recipie_2c1f68_idx'), models.Index(fields=['notification_type', 'target_id', 'recipient'], name='project_not_notific_087203_idx'), models.Index(fields=['recipient', 'is_read'], name='project_not_recipie_3988eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationFetchTracker',
            fields=[
                ('tracker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_fetch_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_notifications_fetch_tracker',
                'indexes': [models.Index(fields=['user', 'last_fetch_at'], name='project_not_user_id_d1c59e_idx')],
            },
        ),
    ]
